== How to make a perfect ristretto with Nespresso^(R)^ coffee maker
:Author:    Zuzana Zoubkova
:Email:     zzoubkov@redhat.com
:Date:      17 Oct 2019

So you have bought your new Nespresso^(R)^ machine and you are wondering how to make a perfect ristretto. No worries! Just follow this easy tutorial and you will enjoy a ristretto made by you in seconds.

1. Fill the water tank with water.
2. Switch on your Nespresso^(R)^ coffee maker – the control buttons will start flashing. Steady light means the coffee maker is heated up and ready.
3. Choose your favourite cup and place it under the coffee outlet.
4. Lifting the handle up open the coffee maker and insert a coffee capsule of your choice. Close the coffee maker pushing the handle down.
5. Push Ristretto control button (25 ml). +
*Important*: You can choose the size of coffee even when the machine is not ready yet, the coffee will flow automatically when the heating process finishes.
6. If you need to stop the coffee flow touch the control button again.
7. Enjoy your coffee! :)


TIP: Before you insert the coffee capsule in your coffee machine, run it for a couple of times to flush out any residual grind and heat up the capsule contact points. +
 +
This enables _easier capsule piercing_ and helps _regulate the amount of coffee that flows out_. Meaning a smoother pour and more coffee in your cup!
